@chapter Constraint Functions

@node ConstMatrix,ConstMatrixM,,Constraint Functions
@section @code{ConstMatrix}
@findex ConstMatrix

@table @t
@item ConstMatrix[@var{m}_,@var{st}_]
::a matrix part of a constraint function of a specific vertex you choice
@end table

@table @var
@item @var{m}
vertex
@item @var{st}
list of start coordinates
@item return
matrix
@end table

@node ConstMatrixM,ConstVectorM,ConstMatrix,Constraint Functions
@section @code{ConstMatrixM}
@findex ConstMatrixM

@table @t
@item ConstMatrixM[@var{st}_,@var{en}_,@var{tri}_,@var{t}_]
::a matrix part of a constraint function of barycenter
@end table

@table @var
@item @var{st}
list of start coordinates
@item @var{en}
list of end coordinates
@item @var{tri}
list of triangulation
@item @var{t}
parameter of time(0...1)
@item return
matrix
@end table

@example
[Example] 
ConstMatrixM[dataS2,dataE2,dataT2,0.5]@math{=}
@{@{1/16, 0, 1/16, 0, 1/16, 0, 1/16, 0@},
@{0, 1/16, 0, 1/16, 0, 1/16, 0, 1/16@},
@{1/16, 0, 1/16, 0, 1/16, 0, 1/16, 0@},
@{0, 1/16, 0, 1/16, 0, 1/16, 0, 1/16@},
@{1/16, 0, 1/16, 0, 1/16, 0, 1/16, 0@},
@{0, 1/16, 0, 1/16, 0, 1/16, 0, 1/16@}, 
@{1/16, 0, 1/16, 0, 1/16, 0, 1/16, 0@}, 
@{0, 1/16, 0, 1/16, 0, 1/16, 0, 1/16@}@}
@c @image{img/RoachGraph,,4cm}
@end example

@node ConstVectorM,ConstfixMatrix,ConstMatrixM, Constraint Functions
@section @code{ConstVectorM}
@findex ConstVectorM

@table @t
@item ConstVectorM[@var{st}_,@var{en}_,@var{tri}_,@var{t}_]
::a vector part of a constraint function of barycenter
@end table

@table @var
@item @var{st}
list of start coordinates
@item @var{en}
list of end coordinates
@item @var{tri}
list of triangulation
@item @var{t}
parameter of time(0...1)
@item return
vector
@end table

@example
[Example] 
ConstVectorM[dataS2,dataE2,dataT2,0.5]@math{=}
@{-0.0625, -0.171875, -0.0625, -0.171875, -0.0625, -0.171875, -0.0625, -0.171875@}
@c @image{img/RoachGraph,,4cm}
@end example


@node ConstfixMatrix,ConstfixVector,ConstVectorM, Constraint Functions
@section @code{ConstfixMatrix}
@findex ConstfixMatrix

@table @t
@item ConstfixMatrix[@var{n}_,@var{k}_,@var{l}_,@var{st}_]
::a matrix part of a constraint function fixing user - specified vector
@end table

@table @var
@item @var{n}
weight of constraint function
@item @var{k},@var{l}
Choice two numbers you want to fix.
@item @var{st}
list of start coordinates
@item return
matrix
@end table

@example
[Example] 
ConstfixMatrix[2,1,2,dataS2]@math{=}
@{@{2, 0, -2, 0, 0, 0, 0, 0@},
@{0, 2, 0, -2, 0, 0, 0, 0@}, 
@{-2, 0, 2, 0, 0, 0, 0, 0@}, 
@{0, -2, 0, 2, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}@}
@c @image{img/RoachGraph,,4cm}
@end example


@node ConstfixVector,ConstPair,ConstfixMatrix, Constraint Functions
@section @code{ConstfixVector}
@findex ConstfixVector

@table @t
@item ConstfixVector[@var{n}_,@var{k}_,@var{l}_,@var{st}_]
::a vector part of a constraint function fixing user - specified vector
@end table

@table @var
@item @var{n}
weight of constraint function
@item @var{k},@var{l}
Choice two numbers you want to fix.
@item @var{st}
list of start coordinates
@item return
vector
@end table

@example
[Example] 
ConstfixVector[2,1,2,dataS2]@math{=}@{2, -6, -2, 6, 0, 0, 0, 0@}
@c @image{img/RoachGraph,,4cm}
@end example

@node ConstPair,ConstPair,ConstfixVector,Constraint Functions
@section @code{ConstPair}
@findex ConstPair

@table @t
@item ConstPair[@var{m}_]
::a pair of matrix and vector of a constraint function of a specific vertex you choice
@end table

@table @var
@item @var{m}
choice of vertex
@item return
@{matrix,vector@}
@end table

@example
[Example] 
ConstPair[1][Configuration,s]@math{=}
@{@{@{1, 0, 0, 0, 0, 0, 0, 0@},
@{0, 1, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}@}, 
@{-2 (-1 + 3 s), -2 (1 + s), 0, 0, 0, 0, 0, 0@}@}
@c @image{img/RoachGraph,,4cm}
@end example


@node ConstPair,DoubleMatrix,ConstPair,Constraint Functions
@section @code{ConstPair}
@findex ConstPair

@table @t
@item ConstPair[@var{m}_,@var{n}_]
::a pair of matrix and vector of a constraint function of a specific two vertices you choice
@end table

@table @var
@item @var{m},@var{n}
choice of vertex
@item return
@{matrix,vector@}
@end table

@example
[Example] 
ConstPair[1,2][Configuration2,s]@math{=}
@{@{@{1, 0, 0, 0, 0, 0, 0, 0@},
@{0, 1, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 1, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 1, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}, 
@{0, 0, 0, 0, 0, 0, 0, 0@}@},
@{-2 (-1 + 3 s), -2 (1 + s), -6 s, -2 (-2 (1 - s) + 4 s), 0, 0, 0, 0@}@}
@c @image{img/RoachGraph,,4cm}
@end example


@node DoubleMatrix,,ConstPair,Constraint Functions
@section @code{DoubleMatrix}
@findex DoubleMatrix

@table @t
@item DoubleMatrix[@var{m}_]
::Return matrix appearing elements and 0 in turn.
@end table

@table @var
@item @var{m}
matrix
@item return
matrix
@end table

@example
[Example] 
DoubleMatrix[@{@{1, 2@}, @{3, 4@}@}]@math{=}
@{@{1, 0, 2, 0@}, @{0, 1, 0, 2@}, @{3, 0, 4, 0@}, @{0, 3, 0, 4@}@}
@c @image{img/RoachGraph,,4cm}
@end example

