@chapter Grobal Interpolations

@node QuadraticFormAlexa,QuadraticFormSim,,Grobal Interpolations
@section @code{QuadraticFormAlexa}
@findex QuadraticFormAlexa

@table @t
@item QuadraticFormAlexa[@var{local}_,@var{conf}_]
::Compute a global error function of Alexa's method.
@end table

@table @var
@item @var{local}
choice of local interpolation
@item @var{conf}
configuration
@item return
@{matrix,vector@}
@end table


@node QuadraticFormSim,ARAPa,QuadraticFormAlexa,Grobal Interpolations
@section @code{QuadraticFormSim}
@findex QuadraticFormSim

@table @t
@item QuadraticFormSim[@var{local}_,@var{conf}_]
::
@end table

@table @var
@item @var{local}
choice of local interpolation
@item @var{conf}
configuration
@item return
@{matrix,vector@}
@end table


@node ARAP,,QuadraticFormSim,Grobal Interpolations
@section @code{ARAP}
@findex ARAP

@table @t
@item ARAP[@var{local}_,@var{energy}_,@var{const}_,@var{conf}_]
::
@end table

@table @var
@item @var{local}
choice of local interpolation
@item @var{energy}
choice of energy function
@item @var{const}
choice of constraint function
@item @var{conf}
configuration
@item return
@{matrix,vector@}
@end table

@example
[Example] 
ARAP[LocalPolar,QuadraticFormAlexa,Const[1],Configuration2]
@c @image{img/RoachGraph,,4cm}
@end example
