@chapter Grobal Interpolations

@node QuadraticFormAlexa,QuadraticFormSim,,Grobal Interpolations
@section @code{QuadraticFormAlexa}
@findex QuadraticFormAlexa

@table @t
@item QuadraticFormAlexa[@var{local}_,@var{conf}_]
::a error function using Alexa's method
@end table

@table @var
@item @var{local}
choice of local interpolation
@item @var{conf}
configuration
@item return
@{matrix,vector@}
@end table


@node QuadraticFormSim,ARAPa,QuadraticFormAlexa,Grobal Interpolations
@section @code{QuadraticFormSim}
@findex QuadraticFormSim

@table @t
@item QuadraticFormSim[@var{local}_,@var{conf}_]
::a error function using similarity preserving method
@end table

@table @var
@item @var{local}
choice of local interpolation
@item @var{conf}
configuration
@item return
@{matrix,vector@}
@end table


@node ARAP,,QuadraticFormSim,Grobal Interpolations
@section @code{ARAP}
@findex ARAP

@table @t
@item ARAP[@var{local}_,@var{energy}_,@var{const}_,@var{conf}_]
::a global error function in matrix form
@end table

@table @var
@item @var{local}
choice of local interpolation
@item @var{energy}
choice of energy function
@item @var{const}
choice of constraint function
@item @var{conf}
configuration
@item return
@{matrix,vector@}
@end table

@example
[Example] 
ARAP[LocalPolar,QuadraticFormAlexa,ConstPair[1],Configuration2][1]@math{=}
@{@{@{2, 0, -(1/4), 0, 0, 0, -(3/4), 0@},
@{0, 2, 0, -(1/4), 0, 0, 0, -(3/4)@},
@{-(1/4), 0, 1/4, 0, -(1/4), 0, 1/4, 0@},
@{0, -(1/4), 0, 1/4, 0, -(1/4), 0, 1/4@},
@{0, 0, -(1/4), 0, 1, 0, -(3/4), 0@},
@{0, 0, 0, -(1/4), 0, 1, 0, -(3/4)@}, 
@{-(3/4), 0, 1/4, 0, -(3/4), 0, 5/4, 0@},
@{0, -(3/4), 0, 1/4, 0, -(3/4), 0, 5/4@}@}, 
@{-6.5, -6., -1., 0.5, 3.5, -4., 8.88178*10^-16, 5.5@}@}
@c @image{img/RoachGraph,,4cm}
@end example
