@chapter Local Interpolations

@node RotateAngle,NewfindMatrices,,LocalInterpolations
@section @code{RotateAngle}
@findex RotateAngle

@table @t
@item RotateAngle[@var{m}_,@var{flag}_]
::controlled rotate angle of m by flag 
@end table

@table @var
@item @var{m}
matrix
@item @var{flag}
1 or 0 or -1, control the rotate angle
@item return
angle
@end table

@node NewFindMatrices,LocalLinear,RotateAngle,LocalInterpolations
@section @code{NewFindMatrices}
@findex NewFindMatrices

@table @t
@item NewFindMatrices[@var{conf}_]
::find matrices converted each triangles
@end table

@table @var
@item @var{conf}
configuration
@item return
matrices 
@end table 

@example
[Example] 
NewFindMatrices[Configuration2]@math{=}
@{@{@{-(5/4), -(3/4)@}, @{-1, -1@}@}, @{@{-(7/4), -(3/4)@}, @{2, -1@}@}@}
@c @image{img/RoachGraph,,4cm}
@end example

@node LocalLinear,LocalPolar,NewFindMatrices,LocalInterpolations
@section @code{LocalLinear}
@findex LocalLinear

@table @t
@item LocalLinear[@var{m}_]
::a local linear interpolations depend on time
@end table

@table @var
@item @var{m}
matrices computed by NewFindMatrices[@var{conf_}]
@item return
matrices of local linear interpolation
@end table

@example
[Example] 
LocalLiner[NewFindMatrices[Configuration2]][0.5]@math{=}
@{@{@{-0.125, 0.125@}, @{-0.5, -0.5@}@}, @{@{-0.875, -0.375@}, @{1.5, 0.@}@}@}
@c @image{img/RoachGraph,,4cm}
@end example

@node LocalPolar,LocalAlexa,LocalLinear,LocalInterpolations
@section @code{LocalPolar}
@findex LocalPolar

@table @t
@item LocalPolar[@var{m}_]
::a local polar interpolations depend on time
@end table

@table @var
@item @var{m}
matrices computed by NewFindMatrices[@var{conf_}]
@item return
matrices of local polar interpolation
@end table

@node LocalAlexa,LocalLogExp,LocalPolar,LocalInterpolations
@section @code{LocalAlexa}
@findex LocalAlexa

@table @t
@item LocalAlexa[@var{m}_]
::a local ARAP interpolations depend on time
@end table

@table @var
@item @var{m}
matrices computed by NewFindMatrices[@var{conf_}]
@item return
matrices of local alexa interpolation
@end table

@node LocalLogExp,LocalInterpolations,LocalAlexa,LocalInterpolations
@section @code{LocalLogExp}
@findex LocalLogExp

@table @t
@item LocalLogExp[@var{m}_]
::a local log-exp interpolations depend on time
@end table

@table @var
@item @var{m}
matrices computed by NewFindMatrices[@var{conf_}]
@item return
matrices of local log-exp interpolation
@end table

@node LocalInterpolations,LocalInterpolations,RotateAngle, Special Graphs
@section @code{LocalInterpolations}
@findex LocalInterpolations

@table @t
@item LocalInterpolations[@var{local}_,@var{conf}_]
::local interpolations that you choice
@end table

@table @var
@item @var{local}
LocalLinear/LocalPolar/LocalAlexa/LocalLogExp
@item @var{conf}
configuration
@item return
@end table

@example
[Example] 
LocalInterpolations[LocalPolar,Configuration2][t]@math{=}
@{@{@{(1 + 0.352786 t) Cos[3.03094 t] + 0.855844 t Sin[3.03094 t], 
0.855844 t Cos[3.03094 t] + (1 - 0.0889399 t) Sin[3.03094 t]@}, 
@{0.855844 t Cos[3.03094 t] - 1. (1 + 0.352786 t) Sin[3.03094 t],
(1 - 0.0889399 t) Cos[3.03094 t] - 0.855844 t Sin[3.03094 t]@}@},
@{@{(1 + 1.65165 t) Cos[2.35619 t] + 0.176777 t Sin[2.35619 t], 
-0.176777 t Cos[2.35619 t] - 1. (1 + 0.237437 t) Sin[2.35619 t]@}, 
@{-0.176777 t Cos[2.35619 t] + (1 + 1.65165 t) Sin[2.35619 t], 
(1 + 0.237437 t) Cos[2.35619 t] - 0.176777 t Sin[2.35619 t]@}@}@}
@c @image{img/RoachGraph,,4cm}
@end example

